### PR TITLE
Fixes for when cone sets are not ranges

### PR DESCRIPTION
**Pull request by joehuchette**
The MPB interface does not require that the cone sets are specified with ranges, and this behavior broke when I passed in e.g. vectors of indices. Hopefully this doesn't break anything with Convex.jl.

### CODE REVIEW

**Comment by joehuchette** [comment]
@ulfworsoe does this seem reasonable?

**Comment by ulfworsoe** [comment]
Sorry it took so long. It looks good. I'll merge.

**Comment by ulfworsoe** [comment]
It looks like this commit is causing some errors in the conic interface. Specifically, the columns of the coefficient matrix are shuffled.

**Comment by ulfworsoe** [comment]
I found the problem; it was a wrong permutation of the bound keys/values for variables.

**Pull request merged**
