### PR TITLE
Allow traditional Mosek variable names

### PR DESCRIPTION
**Pull request by omus**
Convenience change which allows users to use the Mosek C API option names.

### CODE REVIEW

**Comment by mlubin** [comment]
These parameter names are pretty verbose, but I guess there's not much harm in allowing both forms. Could you update the readme as well?

**Comment by omus** [comment]
I agree they are quite verbose. Having the C API names around just makes porting code simpler. I'll update the README.

**Comment by wflu** [comment]
There is no absolute guarantee that the parameter base-names will be unique among all parameters, but it is highly unlikely that it will happen. I have no objection. I will merge it tomorrow.

**Comment by mlubin** [comment]
@wflu, the current implementation infers ``[I|D|S]PAR`` based on the type that the user provides for the parameter, so that's not really an issue unless there's an error in the type of the value.

**Pull request merged**
