### PR TITLE
Fix function call deprecation warnings.

### PR DESCRIPTION
**Pull request by iamed2**
I was getting lots of warnings like this one:

```bash
WARNING: deprecated syntax "f (" at /Users/ericdavies/.julia/v0.4/Mosek/src/msk_callback.jl:7.
Use "f(" instead.
```

Now they're gone!

### CODE REVIEW

**Comment by joehuchette** [comment]
Thanks for doing this! Strangely, the changes to src/msk_functions.jl don't seem to be showing up in the diff.

**Comment by iamed2** [comment]
You're welcome! Luckily the commit includes them and Github recognizes that there are in fact changes; it must just be a problem with the algorithm that chooses what to display.

**Comment by joehuchette** [comment]
https://patch-diff.githubusercontent.com/raw/JuliaOpt/Mosek.jl/pull/51.patch looks good :+1:

**Comment by mlubin** [comment]
@ulfworsoe, does this need changes in the wrapper generator as well?

**Comment by ulfworsoe** [comment]
I don't see any warnings when installing or loading Mosek in v0.4. If anything start popping up let me know.

**Pull request merged**
