### PR TITLE
Sigint2

### PR DESCRIPTION
**Pull request by ulfworsoe**
@mlubin, could you do a sanity check on this.

This is my proposal for ctrl-c handling. As far as I can figure out this should work in Julia 0.4 and appears to work in the nightly pre-0.5 build. It should work as long as it is guaranteed that callbacks happen in the same thread as the initial ``ccall`` (which should always be the case for MOSEK).

It disables sigint for all functions and checks for ctrl-c events in some functions (readdata, writedata, and optimize).

The magic check for ctrl-c happens here: https://github.com/JuliaOpt/Mosek.jl/compare/sigint2?expand=1#diff-9596b489e3ddd922b5fdc83e4c6852b3R30

### CODE REVIEW

**Comment by mlubin** [comment]
CC @tkelman who might have a better idea if this is kosher

**Comment by tkelman** [comment]
Not really, this is Jameson/SGJ/Yichao territory.

**Comment by mlubin** [comment]
CC @vtjnash

**Comment by vtjnash** [comment]
it looks valid to me

**Pull request merged**
