### PR TITLE
fix setbvec!

### PR DESCRIPTION
**Pull request by chriscoey**
fix conbk type (it was inconsistent and caused an error), and throw error when bvec is wrong length

### CODE REVIEW

**Comment by ulfworsoe** [comment]
Thanks for the fixes.

**Comment by mlubin** [comment]
@ulfworsoe, did you mean to close without merging?

**Comment by ulfworsoe** [comment]
No.

**Comment by mlubin** [comment]
@ulfworsoe, mind if I tag a new release with this version?

**Comment by ulfworsoe** [comment]
Please do, and thank you. It explodes between my hands every time I try to make a release.

**Pull request merged**
