### PR TITLE
getbasis function fix

### PR DESCRIPTION
**Pull request by bstellato**
Fix errors such as 

```ERROR: LoadError: UndefVarError: MSK_SK_LO not defined``` 

in MathProgBase `getbasis` function.

### CODE REVIEW

**Comment by bstellato** [comment]
The checks seem to be failing because travis has an outdated Mosek license

**Comment by odow** [comment]
Yes, @ulfworsoe updates [this special MOSEK license](https://github.com/JuliaOpt/Mosek.jl/blob/master/test/.dontuse-probablyexpired.lic) from time to time.

**Comment by ulfworsoe** [comment]
Bit of a hack, I know. I haven't found a better solution yet.

**Comment by odow** [comment]
Maybe you could set the licence as a Travis environment variable and restrict access to Travis?

**Comment by ulfworsoe** [comment]
We have been discussing various options at the office. We can't publish any kind of perpetual license, so no matter what I would have to update it once in a while (e.g. once a month).
The license has be a file, but we could just write the content of the environment variable to a file before running. Or let the test script check for the presence of such a variable.
I will have to discuss with Erling what we can do.

**Pull request merged**
