### PR TITLE
getvardual should work to return infeasible rays

### PR DESCRIPTION
**Pull request by mlubin**
This seems to work to get mosek to return infeasible rays. @ulfworsoe, is there anything unsafe here?

### CODE REVIEW

**Comment by ulfworsoe** [comment]
It should be straight forward. An infeasible ray is just a solution vector.

**Comment by ulfworsoe** [comment]
One thing, though: We should consider if we want to return values for all solution statuses. If solution is a cert. of primal infeasibility, the primal values are arbitrary garbage (but MOSEK will still return them).

We should consider if we want to return this without warning.

**Comment by mlubin** [comment]
I don't think that's a big issue. It's up to users to check the solution
status, though a warning wouldn't hurt.

**Comment by ulfworsoe** [comment]
In that case this should be good.

**Pull request merged**
