### PR TITLE
fix getdual by fixing indexing on conslack

### PR DESCRIPTION
**Pull request by chriscoey**
increment barvarptr after set conslack, not before

need better tests to ensure this fixes the getdual issue

### CODE REVIEW

**Comment by mlubin** [comment]
Ooh, nice detective work

**Comment by chriscoey** [comment]
not getting errors now, and what I get from getdual seems to be reasonable,
but I don't know whether this breaks anything else or if there are still
cases where it will fail.

**Comment by mlubin** [comment]
If the mosek gives valid primal-dual solutions now and it passes strictly more tests than it used to, then looks good. Would like to hear from @ulfworsoe if the fix is valid before we merge though.

**Comment by mlubin** [comment]
I'll merge this so we can continue with our work. @ulfworsoe, when you get a chance please confirm that this fix is correct.

**Pull request merged**
