### PR TITLE
Mpb0.4 impl

### PR DESCRIPTION
**Pull request by ulfworsoe**
Support for MathProgBase 0.4. This splits the model into three different models and removes support for non-convex quadratic constraints in the Linear/Quadratic interface (i.e. qcone and rotated qcone on quadratic form)

@mlubin, there are still some JuMP tests failing. As far as I can see these are related to
- Semicontinuous variables (that MOSEK does not support - treated as normal continuous vars?)
- Quad cone and rotated quad cone constraints in Linear/Quadratic API.

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks @ulfworsoe! Give us a few days to figure out how to handle the issue of cones being passed through the quadratic interface, we'll have to do a transformation at the JuMP level. CC @joehuchette

**Comment by IainNZ** [comment]
So we need to take `x'Qx + a'x <= b` and turn it into SOCs?

**Comment by mlubin** [comment]
No, just x'x <= t^2 (and rotated)

**Comment by mlubin** [comment]
The issue is that we don't want to do this always... if using Gurobi/CPLEX it's better to pass them as quadratic constraints.

**Comment by erling-d-andersen** [comment]
I have not followed the discussion closely but will add my 2 cents.

Using MOSEK v8 you can do following.

Assume you have task (in MOSEK lingo) that has linear and quadratic
functions only. Including something that modeling quadratic cones like
GuRoBi.
That we have function that can create task where all the quadratic
functions has been replaced by cones. You can then solve conic
reformulation obtain a primal solution.
Obtaining a dual solution to the original QCQP we do not even try.














2015-12-03 17:34 GMT+01:00 Miles Lubin <notifications@github.com>:

**Comment by mlubin** [comment]
@erling-d-andersen, that makes sense and will be helpful for us, we don't return duals either if the cones come in quadratic form. Until Mosek v8 is released, we may need to do a small hack to ensure backward compatibility with current JuMP models that use this form.

**Comment by erling-d-andersen** [comment]
I expect a beta of MOSEK v8 comes out early next year.

2015-12-04 16:23 GMT+01:00 Miles Lubin <notifications@github.com>:

**Comment by mlubin** [comment]
@ulfworsoe, I've proposed a PR that will translate quadratic constraints to conic form if using Mosek: https://github.com/JuliaOpt/JuMP.jl/pull/630
That part seems to work, but there are still some test failures:
- ``addconstr!`` and ``addvar!`` fallbacks are missing. It looks like the implementation for ``MosekLinearQuadraticModel`` requires a ``Vector{Int32}`` as input indices, which is not standard.
- The nonlinear tests fail with:
```
[nonlinear] Accepting fixed variables
  > With solver Ipopt.IpoptSolver
  > With solver NLopt.NLoptSolver
  > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
MOSEK error 4010: The specified file format does not support a problem with general nonlinear terms.
ERROR: LoadError: LoadError: Mosek.MosekError(4010,"The specified file format does not support a problem with general nonlinear terms.")
 in writedata at /home/mlubin/.julia/v0.4/Mosek/src/msk7_functions.jl:3783
 in optimize! at /home/mlubin/.julia/v0.4/Mosek/src/MosekLPQCQPInterface.jl:1218
 in solvenlp at /home/mlubin/.julia/v0.4/JuMP/src/nlp.jl:547
 in solve at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:113
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/nonlinear.jl:89
 in context at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/nonlinear.jl:81
 in facts at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/mlubin/.julia/v0.4/JuMP/test/nonlinear.jl, in expression starting on line 79
while loading /home/mlubin/.julia/v0.4/JuMP/test/runtests.jl, in expression starting on line 36
```

**Comment by ulfworsoe** [comment]
Ok. I'll add the missing type-less method instances.

**Comment by ulfworsoe** [comment]
I think I have fixed the issues. There is still one fail in JuMP, and I cannot figure out what it is. The fail is 
``[model] Relaxation keyword argument to solve`` in  JuMP/test/model.jl.
The problem that MOSEK recieves is correct, except it contains two extra variables (objective bounds, maybe?). When those are removed, the solution is what the test expects.

**Comment by mlubin** [comment]
CC @joehuchette

**Comment by joehuchette** [comment]
Hmm that's strange, the relaxation test passes for me locally.

**Comment by mlubin** [comment]
I get this failure when running JuMP's tests:
```
[probmod] Testing problem modification basics
  > With solver Gurobi.GurobiSolver
  > With solver CPLEX.CplexSolver
  > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
ERROR: LoadError: LoadError: UndefVarError: addvar! not defined
 in addvar! at /home/mlubin/.julia/v0.4/Mosek/src/MosekLPQCQPInterface.jl:437
 in call at /home/mlubin/.julia/v0.4/JuMP/src/JuMP.jl:632
 [inlined code] from /home/mlubin/.julia/v0.4/JuMP/src/macros.jl:801
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/probmod.jl:24
 in context at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/probmod.jl:23
 in facts at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
```

**Comment by ulfworsoe** [comment]
Missing addvar! function has been added.

On Thu, Dec 10, 2015 at 7:50 PM, Miles Lubin <notifications@github.com>
wrote:

> I get this failure when running JuMP's tests:
>
> [probmod] Testing problem modification basics
>   > With solver Gurobi.GurobiSolver
>   > With solver CPLEX.CplexSolver
>   > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
> ERROR: LoadError: LoadError: UndefVarError: addvar! not defined
>  in addvar! at /home/mlubin/.julia/v0.4/Mosek/src/MosekLPQCQPInterface.jl:437
>  in call at /home/mlubin/.julia/v0.4/JuMP/src/JuMP.jl:632
>  [inlined code] from /home/mlubin/.julia/v0.4/JuMP/src/macros.jl:801
>  in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/probmod.jl:24
>  in context at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:474
>  in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/probmod.jl:23
>  in facts at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:448
>  in include at ./boot.jl:261
>  in include_from_node1 at ./loading.jl:304
>  in include at ./boot.jl:261
>  in include_from_node1 at ./loading.jl:304
>  in process_options at ./client.jl:280
>  in _start at ./client.jl:378
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/pull/67#issuecomment-163715403>.
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by mlubin** [comment]
@ulfworsoe, that didn't quite fix it, but this does:
```diff
diff --git a/src/MosekLPQCQPInterface.jl b/src/MosekLPQCQPInterface.jl
index 7324781..3776879 100644
--- a/src/MosekLPQCQPInterface.jl
+++ b/src/MosekLPQCQPInterface.jl
@@ -448,7 +448,7 @@ function MathProgBase.addvar!(m::MosekLinearQuadraticModel,
                               bl  ::Float64,
                               bu  ::Float64,
                               c   ::Float64)
-    addvar!(m,bl,bu,c)
+    MathProgBase.addvar!(m,bl,bu,c)
     Mosek.putacol(m.task,m.numvar,subi,val)
 end
```

Proceeding with the JuMP tests, the next failure is:
```
[probmod] Test adding a 'decoupled' variable (#205)
  > With solver Gurobi.GurobiSolver
  > With solver CPLEX.CplexSolver
  > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
(length(m.buc),length(m.blc)) = (0,0) <-- I added this @show
ERROR: LoadError: LoadError: BoundsError: attempt to access 0-element Array{Float64,1}
  at index [1]
 in setconstrLB! at /home/mlubin/.julia/v0.4/Mosek/src/MosekLPQCQPInterface.jl:304
 in buildInternalModel at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:341
```
The lengths of ``m.buc`` and ``m.blc`` are shorter than the code assumes.

**Comment by ulfworsoe** [comment]
Fixed. There are two tests that fail for me in JuMP now: The relaxation test and a MIP test that fails on precision (I think).

**Comment by mlubin** [comment]
I relaxed the tolerances on the MIP test that was failing (at https://github.com/JuliaOpt/JuMP.jl/pull/630). The relaxation test passes for me, I can't reproduce your failure. However, I do get a failure in the SDP tests:
```
[sdp] Robust uncertainty example
  > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
    > d = 3
      Failure :: (line:-1) :: d = 3 :: fact was false
        Expression: abs(object - exact) --> roughly(0,1.0e-5)
          Expected: 0.14983156076480908 ≅ 0
    > d = 5
    > d = 8
      Failure :: (line:-1) :: d = 8 :: fact was false
        Expression: abs(object - exact) --> roughly(0,1.0e-5)
          Expected: 0.5872923846373936 ≅ 0
```

**Comment by ulfworsoe** [comment]
I can't reproduce that. Which Mosek version/platform are you using?

**Comment by mlubin** [comment]
This was with Mosek 7.1 on 64-bit linux.

**Comment by mlubin** [comment]
@joehuchette, can you reproduce on OS X?

**Comment by joehuchette** [comment]
I'm still getting a bunch of errors like
```
MOSEK error 4010: The specified file format does not support a problem with general nonlinear terms.
ERROR: LoadError: LoadError: Mosek.MosekError(4010,"The specified file format does not support a problem with general nonlinear terms.")
```
and I missing a patch? I'm on JuMP master, this branch for Mosek.jl, and MPB master.

I'm also getting
```
[sdp] Robust uncertainty example
  > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
    > d = 3
      Failure :: (line:505) :: d = 3 :: fact was false
        Expression: abs(object - exact) --> roughly(0,1.0e-5)
          Expected: 0.14983156042541035 ≅ 0
    > d = 5
    > d = 8
      Failure :: (line:505) :: d = 8 :: fact was false
        Expression: abs(object - exact) --> roughly(0,1.0e-5)
          Expected: 0.5872923397745318 ≅ 0
Out of 6 total facts:
  Verified: 4
  Failed:   2
```
like Miles.

**Comment by mlubin** [comment]
To fix ``MOSEK error 4010``, you have to remove the statement writing out the problem from the definition of ``MathProgBase.optimize!``.

**Comment by mlubin** [comment]
@ulfworsoe, are you able to reproduce the SDP issue on Mosek 7?

**Comment by ulfworsoe** [comment]
I have just now reproduced the SDP problem. I was testing against the
mosekhack branch in JuMP.

Wrt. the rouge Task,writedata: removed.

On Wed, Dec 16, 2015 at 6:09 PM, Miles Lubin <notifications@github.com>
wrote:

> @ulfworsoe <https://github.com/ulfworsoe>, are you able to reproduce the
> SDP issue on Mosek 7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Mosek.jl/pull/67#issuecomment-165178148>.
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by ulfworsoe** [comment]
I am trying to figure out what the problem is in the SDP test fail, and so far I cannot find anything wrong. Basically, all constraints are within tolerance (better than 1e-8), and the duality gap is basically 0. On manual inspection I can find no problems with the mapping of the problem either.

Can I get a reference solution somehow?

**Comment by mlubin** [comment]
Well this is bizarre. I copied the exact conic input data that JuMP provides to Mosek.jl into a script (https://gist.github.com/mlubin/2dfc4b2042a24cf652da), and when I run that, Mosek gives the right answer!

I pulled out the JuMP test here (https://gist.github.com/mlubin/9e0909d887c8f0e6071a). Mosek gives the wrong answer here.

How can we compare the internal state of these two models? There's some strange corruption happening somewhere.

**Comment by mlubin** [comment]
@ulfworsoe, I've narrowed down the issue to the following:
In my [example](https://gist.github.com/mlubin/2dfc4b2042a24cf652da) where mosek gives the correct answer, if you add the call
```
MathProgBase.setvartype!(m, fill(:Cont,numvar))
```
before ``optimize!`` then the answer matches the incorrect answer from JuMP. So the issue is somewhere in ``setvartype!``. Clearly, setting all variables to continuous shouldn't change the solution.

**Comment by ulfworsoe** [comment]
Got it. The setvartype! call changes some bounds.

**Comment by ulfworsoe** [comment]
Should be fixed now. 

There are still some tests that fail. Regarding optimality tests: I notice a test in JuMP in sdp.jl ("Test simple SDP") that compares "(trace(B3*YY) <= 0) --> true". This should probably be eps instead of 0 (eps in the order of 1e-6 or 1e-8).

**Comment by ulfworsoe** [comment]
Failing tests.
[nonlinear] Test infeasibility detection: I am not sure about this. I think it may be a kind of bug, because MOSEK should only accept non-linear inequality constraints. We usually recommend that linear terms in non-linear problems are specified in the normal way, but I'm guessing the it might not be so simple to do that from JuMP/

[model] Relaxation keyword argument to solve: A bug in MOSEK. It is on the MIP guy's desk now.

**Comment by mlubin** [comment]
@ulfworsoe we can update the tolerance on that SDP test. The nonlinear failure isn't new, so I'm willing to let that go for now. We'll soon have an easy way to detect if a nonlinear constraint is linear, so once that's available we could pass the linear terms correctly.

**Comment by ulfworsoe** [comment]
@mlubin, In any case the non-linear problem is something that should be handled by MOSEK, so it's not a Mosek.jl bug. I will merge into the master tomorrow if you have no objection.

**Comment by mlubin** [comment]
No objections to merging, thanks!

**Pull request merged**
