### PR TITLE
fixes for MPB 0.4 transition

### PR DESCRIPTION
**Pull request by mlubin**
PR against the mpb0.4-impl branch. Here are a few fixes I needed to get Mosek running with JuMP and Convex.jl on their mpb0.4 branches. Tests are still failing in a number of places.

Note that the new version of MPB requires julia 0.4, so it's okay to drop the dependency on the Compat package and all of the ``@compat`` macros.

### CODE REVIEW

**Comment by ulfworsoe** [comment]
I have merged and fixed some details. There are still some JuMP tests that fail (some non-convex qcqp from inputting cones as quadratic constraints, some others that I'm not sure about).

**Comment by mlubin** [comment]
@ulfworsoe, I'm getting the following failure when testing Convex.jl:
```
julia> using Mosek, Convex

julia> x = Variable(Positive());

julia> y = Variable((3, 3));

julia> p = minimize(x + y[1, 1], isposdef(y), x >= 1, y[2, 1] == 1);

julia> solve!(p, MosekSolver())
Computer
  Platform               : Linux/64-X86    

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 13              
  Cones                  : 0               
  Scalar variables       : 11              
  Matrix variables       : 1               
  Integer variables      : 0               

Optimizer started.
Conic interior-point optimizer started.
Presolve started.
Linear dependency checker started.
Linear dependency checker terminated.
Eliminator - tries                  : 0                 time                   : 0.00            
Eliminator - elim's                 : 0               
Lin. dep.  - tries                  : 1                 time                   : 0.00            
Lin. dep.  - number                 : 0               
Presolve terminated. Time: 0.00    
Optimizer  - threads                : 2               
Optimizer  - solved problem         : the primal      
Optimizer  - Constraints            : 6
Optimizer  - Cones                  : 0
Optimizer  - Scalar variables       : 6                 conic                  : 0               
         
Factor     - setup time             : 0.00              dense det. time        : 0.00            
Factor     - ML order time          : 0.00              GP order time          : 0.00            
Factor     - nonzeros before factor : 21                after factor           : 21              
Factor     - dense dim.             : 0                 flops                  : 3.61e+02        
ITE PFEAS    DFEAS    GFEAS    PRSTATUS   POBJ              DOBJ              MU       TIME  
0   1.0e+00  1.0e+00  1.0e+00  0.00e+00   1.000000000e+00   1.000000000e+00   1.0e+00  0.00  
1   2.6e-01  2.6e-01  2.6e-01  -1.43e-01  1.677505504e+00   2.259680484e+00   2.6e-01  0.00  
2   3.9e-02  3.9e-02  3.9e-02  7.04e-01   1.533927052e+00   1.675943021e+00   3.9e-02  0.00  
3   5.3e-03  5.3e-03  5.3e-03  2.94e-01   1.215515642e+00   1.349369076e+00   5.3e-03  0.00  
4   9.2e-04  9.2e-04  9.2e-04  2.15e-01   1.088549368e+00   1.189293092e+00   9.2e-04  0.00  
5   2.0e-04  2.0e-04  2.0e-04  5.40e-01   1.066338433e+00   1.107630830e+00   2.0e-04  0.00  
6   5.1e-05  5.1e-05  5.1e-05  3.65e-01   1.037469888e+00   1.069285795e+00   5.1e-05  0.00  
7   1.6e-05  1.6e-05  1.6e-05  5.93e-01   1.029900801e+00   1.046498278e+00   1.6e-05  0.00  
8   6.8e-06  6.8e-06  6.8e-06  1.72e-01   1.015623449e+00   1.036836151e+00   6.8e-06  0.00  
9   1.4e-06  1.4e-06  1.4e-06  7.03e-01   1.013632102e+00   1.019837857e+00   1.4e-06  0.00  
10  3.0e-07  3.0e-07  3.0e-07  3.65e-01   1.007283322e+00   1.012308223e+00   3.0e-07  0.00  
11  8.6e-08  8.6e-08  8.6e-08  4.97e-01   1.005162629e+00   1.008159357e+00   8.6e-08  0.00  
12  3.5e-08  3.5e-08  3.5e-08  1.77e-01   1.002790614e+00   1.006306046e+00   3.5e-08  0.00  
13  7.9e-09  7.9e-09  7.8e-09  6.95e-01   1.002411660e+00   1.003522493e+00   7.9e-09  0.00  
14  1.9e-09  1.9e-09  2.0e-09  3.37e-01   1.001281526e+00   1.002274329e+00   1.9e-09  0.00  
15  5.8e-10  5.8e-10  6.4e-10  5.84e-01   1.001006175e+00   1.001508592e+00   5.8e-10  0.00  
16  2.2e-10  2.2e-10  9.8e-11  1.92e-01   1.000518409e+00   1.001135050e+00   2.2e-10  0.00  
17  8.7e-11  5.9e-11  1.1e-11  6.83e-01   1.000439328e+00   1.000702688e+00   5.9e-11  0.00  
18  4.7e-11  4.3e-11  2.3e-11  6.49e-01   1.000418586e+00   1.000632247e+00   4.3e-11  0.00  
19  4.7e-11  4.3e-11  2.3e-11  1.08e-01   1.000418586e+00   1.000632247e+00   4.3e-11  0.01  
Interior-point optimizer terminated. Time: 0.01. 

Optimizer terminated. Time: 0.01    
ERROR: Mosek.MosekMathProgSolverInterface.MosekMathProgModelError("No solution available")
 in getsolution at /home/mlubin/.julia/v0.4/Mosek/src/MosekConicInterface.jl:430
 in populate_solution! at /home/mlubin/.julia/v0.4/Convex/src/solution.jl:100
 in solve! at /home/mlubin/.julia/v0.4/Convex/src/solution.jl:36
 in solve! at /home/mlubin/.julia/v0.4/Convex/src/solution.jl:13
```

**Comment by mlubin** [comment]
This is with mosek 7.1

**Comment by ulfworsoe** [comment]
It looks like it solves fine, so probably an interface bug.

**Comment by mlubin** [comment]
Also the following failure in JuMP's tests:
```
[sdp] Test simple SDP
  > With solver Mosek.MosekMathProgSolverInterface.MosekSolver
ERROR: LoadError: LoadError: BoundsError: attempt to access 0-element Array{Int32,1}
  at index [7]
 in setvartype! at /home/mlubin/.julia/v0.4/Mosek/src/MosekConicInterface.jl:565
 in buildInternalModel at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:284
 in solve at /home/mlubin/.julia/v0.4/JuMP/src/solvers.jl:81
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/sdp.jl:20
 in context at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/test/sdp.jl:6
 in facts at /home/mlubin/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/mlubin/.julia/v0.4/JuMP/test/sdp.jl, in expression starting on line 4
```

**Comment by ulfworsoe** [comment]
I have tested, and it looks like the solver in the latest distro stalls and reports status:unknown. I can see the latest internal build of Mosek 7.1 reports status:near_optimal, so it is probably a border-line case.

**Pull request closed without merging**
